In [2]:
import os
import pandas as pd 
path = 'C:/Users/shh28/BigLeader/3주차/수업자료/머신러닝(고우주)/고우주-1일차/02_Regression/data/서울_연립다세대_매매'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.csv')]

file_list_py

['연립다세대(매매)__실거래가_2010.csv',
 '연립다세대(매매)__실거래가_2011.csv',
 '연립다세대(매매)__실거래가_2012.csv',
 '연립다세대(매매)__실거래가_2013.csv',
 '연립다세대(매매)__실거래가_2014.csv',
 '연립다세대(매매)__실거래가_2015.csv',
 '연립다세대(매매)__실거래가_2016.csv',
 '연립다세대(매매)__실거래가_2017.csv',
 '연립다세대(매매)__실거래가_2018.csv',
 '연립다세대(매매)__실거래가_2019.csv',
 '연립다세대(매매)__실거래가_2020.csv',
 '연립다세대(매매)__실거래가_2021.csv']

In [3]:
df = pd.DataFrame()
for i in file_list_py:
    data = pd.read_csv(i,encoding='cp949',skiprows=15)
    df = pd.concat([df,data])
df = df.reset_index(drop = True)

In [4]:
df

,시군구,번지,본번,부번,건물명,전용면적(㎡),대지권면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일
0,서울특별시 강남구 개포동,170-18,170,18,(170-18),26.60,21.53,201007,13,"29,350",1,1988.0,선릉로12길 17,NaN
1,서울특별시 강남구 개포동,1219-11,1219,11,강남하이츠,39.90,19.33,201001,22,"21,500",1,1993.0,개포로20길 35,NaN
2,서울특별시 강남구 개포동,1202-2,1202,2,경모하이츠,51.69,21.20,201003,12,"28,500",1,1991.0,개포로22길 41-6,NaN
3,서울특별시 강남구 개포동,1235-16,1235,16,광현빌라,62.76,34.53,201001,22,"36,500",2,2001.0,논현로18길 10-13,NaN
4,서울특별시 강남구 개포동,1235-16,1235,16,광현빌라,77.34,42.55,201011,2,"44,200",4,2001.0,논현로18길 10-13,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493350,서울특별시 중랑구 중화동,86-9,86,9,화수분빌리지(105),55.58,27.57,202103,4,"17,000",2,2003.0,봉화산로21길 15,NaN
493351,서울특별시 중랑구 중화동,307-4,307,4,화인하우스(307-4),54.32,27.24,202102,17,"38,800",7,2017.0,동일로139가길 22,NaN
493352,서울특별시 중랑구 중화동,307-4,307,4,화인하우스(307-4),56.51,28.34,202102,19,"38,000",5,2017.0,동일로139가길 22,NaN
493353,서울특별시 중랑구 중화동,15-2,15,2,휴렉스빌,29.44,18.14,202104,6,"17,500",4,2016.0,봉화산로27다길 6,NaN
493354,서울특별시 중랑구 중화동,15-2,15,2,휴렉스빌,29.27,18.14,202106,8,"18,500",3,2016.0,봉화산로27다길 6,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 493355 entries, 0 to 493354
Data columns (total 14 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   시군구       493355 non-null  object
 1   번지        493321 non-null  object
 2   본번        493355 non-null  int64
 3   부번        493355 non-null  int64
 4   건물명       493355 non-null  object
 5   전용면적(㎡)   493355 non-null  float64
 6   대지권면적(㎡)  493355 non-null  float64
 7   계약년월      493355 non-null  int64
 8   계약일       493355 non-null  int64
 9   거래금액(만원)  493355 non-null  object
 10  층         493355 non-null  int64
 11  건축년도      493334 non-null  float64
 12  도로명       493355 non-null  object
 13  해제사유발생일   4464 non-null    float64
dtypes: float64(4), int64(5), object(5)
memory usage: 52.7+ MB